apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: acquisition
  labels:
    app: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend # POD name that will be handled by replicaset
  template: # Template to create the POD
    metadata:
      labels:
        app: backend
    spec:
      # --- INIT CONTAINER ---
      initContainers:
        - name: migrate
          image: acquisitions-app:latest # MUST MATCH backend image
          imagePullPolicy: IfNotPresent
          command: ['npx', 'prisma', 'migrate', 'deploy']
          securityContext:
            runAsUser: 0 # RUN AS ROOT (important)
          env:
            - name: DATABASE_URL
              value: 'postgresql://acquisition_db_user:acquisition_password@postgress:5432/acquisition_db?schema=public'

      # --- MAIN APP CONTAINER ---
      containers:
        - name: backend
          image: acquisitions-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432 # INSIDE container app â†’ listens on port 5432
          env:
            - name: DATABASE_URL
              value: 'postgresql://acquisition_db_user:acquisition_password@postgress:5432/acquisition_db?schema=public'
            - name: PORT
              value: '3000'
            - name: NODE_ENV
              value: 'development'
            - name: LOG_LEVEL
              value: 'info'
            - name: ARCJET_KEY
              value: 'ajkey_01k8bdzhijklxsn7pv1hge22mj'
            - name: JWT_SECRET
              value: 'my_super_secret_key'
          readinessProbe: # Only ready pods are added to service endpoints
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe: # Tell kubelet whether container is alive or not
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: acquisition
spec:
  selector:
    app: backend # POD name that will be handled by replicaset
  ports:
    - protocol: TCP
      port: 3000 # Service receives traffic on 5432
      targetPort: 3000 # Then forwards to POD on 5432
  type: ClusterIP # Exposes a stable IP inside a cluster
