apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: acquisition
data:
  PORT: '3000'
  NODE_ENV: 'production'
  LOG_LEVEL: 'info'
  POSTGRES_USER: 'acquisition_db_user'
  POSTGRES_DB: 'acquisition_db'
