apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: acquisition
type: Opaque # Generic key value secret
data:
  JWT_SECRET: bXlfc3VwZXJfc2VjcmV0X2tleQ==
  ARCJET_KEY: YWprZXlfMDFrOGJkemhpamtseHNuN3B2MWhnZTIybWo=
  POSTGRES_PASSWORD: YWNxdWlzaXRpb25fcGFzc3dvcmQ=
